### ISSUE TITLE
How to extend zenpacklib classes from different ZenPacks?

### ISSUE THREAD

**Issue by BigChief45** [zenoss/ZenPacks.zenoss.ZenPackLib#433]
I am trying to achieve something similar to what's discussed in [this issue](https://github.com/zenoss/ZenPacks.zenoss.ZenPackLib/issues/106). 

Basically I have one ZenPack that creates a custom class that inherits from `zenpacklib.Device`:

```yaml
# FirstZenPack
device_classes:
   /Server/MyDeviceClass:
      zProperties:
         zPythonClass: ZenPacks.bigchief.FirstZenPack.MyServer

classes:
   MyServer:
      base: [zenpacklib.Device]
      label: My Server
      properties:
         # ...
```

Then I have a second ZenPack where I want to extend the same `MyServer` class above from the first ZenPack and **add** new properties to the existing class. However I do not know how to do this using zenpacklib. I have tried the following without any success:

```yaml
# SecondZenPack
classes:
   MyServer:
      base: [ZenPacks.bigchief.FirstZenPack.MyServer]
      properties:
         new_property:
            type: boolean
            default: true
```
